name: Deploy

on:
  push:
    branches:
      - main
      - develop
      - prod

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  REPO_NAME: ${{ github.event.repository.name }} # you can hardcode this if you want in the env variables
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true #https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name and save to service name
        shell: bash
        id: extract_branch
        run: echo "::set-env name=SERVICE_NAME::$(echo ${GITHUB_REF#refs/heads/})-$REPO_NAME"

      - name: Print service name
        run: echo $SERVICE_NAME

      - run: "echo '${{ secrets.SA_KEY_JSON }}' > gcp_credentials.json"
        shell: bash

      - run: "echo '${{ secrets.TWITTER_KEY }}' > twitter_credentials.json"
        shell: bash

      # Runs a single command using the runners shell
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.10.1
        with:
          credentials: ${{ secrets.SA_KEY_JSON }}
          name: ${{ github.event.repository.name }}
          project_id: ${{ secrets.PROJECT_ID }}
          # name of our function in our main.py file, defaults to the resource name suffix 
          entry_point: Exract_Twitter_Data
          # runtime to use for the function
          runtime: python310
