name: Deploy

on:
  push:
    branches:
      - main
      - develop
      - prod

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  REPO_NAME: ${{ github.event.repository.name }} # you can hardcode this if you want in the env variables

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name and save to service name
        shell: bash
        id: extract_branch
        run: echo "::set-env name=SERVICE_NAME::$(echo ${GITHUB_REF#refs/heads/})-$REPO_NAME"

      - name: Print service name
        run: echo $SERVICE_NAME

      - run: "echo '${{ secrets.SA_KEY_JSON }}' > gcp_credentials.json"
        shell: bash

      - run: "echo '${{ secrets.TWITTER_KEY }}' > twitter_credentials.json"
        shell: bash

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.SA_KEY_JSON }}
          project_id: ${{ secrets.PROJECT_ID }}

      # Deploy image to Cloud Function
      - name: Deploy
        run: |-
          gcloud functions deploy "$SERVICE_NAME" \
            --quiet \
            --runtime python310 \
            --trigger-http \
            --entry-point Exract_Twitter_Data
